version: '2'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trackmyfuel
      MYSQL_USER: track
      MYSQL_PASSWORD: pass

volumes:
  mysql-data: {}